### ISSUE TITLE
Can a field have alternate language without primary language

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-xml#11]
The schema seems to allow it, eg 
```
<cit:name xsi:type="lan:PT_FreeText_PropertyType">

  <!-- REMOVED: <gco:CharacterString>acknowledgement in french</gco:CharacterString> -->

  <lan:PT_FreeText>
    <lan:textGroup>
      <lan:LocalisedCharacterString locale="eng">acknowledgement in english</lan:LocalisedCharacterString>
    </lan:textGroup>
  </lan:PT_FreeText>
</cit:name>
```

Or do we say if there's alternate text given then there has to be text in the default language

**Comment by fostermh** [comment]
if the value is required then I think this example should fail validation.
If the value is not required then its the same as not having a value at all.

from https://schemas.isotc211.org/19115/-3/lan/1.0/language.xsd

"PT_FreeText can't substitute for CharacterString because that is a simple
type; have to extend the property type so that instance docs will still
have a CharacterString Element, and a textGroup with
localisedCharacterStrings"

which implies to me that you can't have a PT_FreeText without a
CharacterString.

Matthew Foster
Hakai Institute, Calvert Island, BC, Canada / www.hakai.org
Tula Foundation, Quadra Island, BC, Canada / www.tula.org

**Comment by n-a-t-e** [comment]
To clarify my question - the given XML does pass validation, I was more wondering if logically it makes sense to allow it, eg would there be a case where a french language record might have a few fields with only english text?

It would simplify things to not allow it, which is what I've been going with so far.

I think that schema comment about `PT_FreeText` is just an explanation why `PT_FreeText` can't have `substitutionGroup="gco:CharacterString"` in it's definition

**Comment by fostermh** [comment]
Ah I see, how awkward of it.

I am in favour of not allow it personally.

Matthew Foster
Hakai Institute, Calvert Island, BC, Canada / www.hakai.org
Tula Foundation, Quadra Island, BC, Canada / www.tula.org

**Comment by n-a-t-e** [comment]
I'm closing this because it's not very important
